### PR TITLE
Feature: Add support for Candle chain

### PR DESCRIPTION
**Pull request by samisbakedham**

### CODE REVIEW

**Comment by nchamo** [comment]
Hey @samisbakedham !

Nice to meet you, and thank you for doing this. If I understand correctly, you'd like for Mean to be deployed to Candle chain, right?

If you don't mind, can I ask you a few questions about Candle?
1. Are there Chainlink oracles available on Candle?
2. I don't think it is, but is Uniswap v3 deployed on Candle?
3. Can you tell us a little bit about the different DEXes on Candle?
4. Are there any DEX aggregators there?

I'm asking all these questions because these are different services and protocols that Mean needs in order to work correctly

**Comment by samisbakedham** [comment]
> Hey @samisbakedham !
> 
> 
> 
> Nice to meet you, and thank you for doing this. If I understand correctly, you'd like for Mean to be deployed to Candle chain, right?
> 
> 
> 
> If you don't mind, can I ask you a few questions about Candle?
> 
> 1. Are there Chainlink oracles available on Candle?
> 
> 2. I don't think it is, but is Uniswap v3 deployed on Candle?
> 
> 3. Can you tell us a little bit about the different DEXes on Candle?
> 
> 4. Are there any DEX aggregators there?
> 
> 
> 
> I'm asking all these questions because these are different services and protocols that Mean needs in order to work correctly

Hey!
1) Yes, Chainlink hasn't pushed them to their web yet though. 
2) A fork of it is
3) There's just one for now, https://dex.cndlchain.com
4) Li.Fi should be live in a week or two

**Comment by nchamo** [comment]
Hey @samisbakedham !

That's good news. Just to confirm, is [dex.cndlchain.com](https://dex.cndlchain.com/) the fork you mention in (2)?

Also, is there a place to get TVL and volume metrics?

**Comment by samisbakedham** [comment]
> Hey @samisbakedham !
> 
> 
> 
> That's good news. Just to confirm, is [dex.cndlchain.com](https://dex.cndlchain.com/) the fork you mention in (2)?
> 
> 
> 
> Also, is there a place to get TVL and volume metrics?

Yes, and yes it'll be up soon under analytics on the dex!

**Comment by nchamo** [comment]
That's great. This issue has been a great exercise for us, so that we can list exactly what we use as a protocol:

**Needs**:
1. Chainlink or Uniswap v3 oracles with a good TVL
1. Bridge to send funds over 

**Would prefer (would require some effort on our side to make it work without this)**:
1. A DEX aggregator that supports 'exact in' and 'exact out' quotes
1. Support on Defi Llama prices API (https://defillama.com/docs/api)
1. Support on OZ Defender (https://www.openzeppelin.com/defender)

@0xged , can you think of something else?

**Comment by 0xged** [comment]
Hey guys! @samisbakedham thanks for raising the idea of Candle deployment.

Having `The Graph` deployed in the network is also a must.

**Comment by samisbakedham** [comment]
> Hey guys! @samisbakedham thanks for raising the idea of Candle deployment.
> 
> 
> 
> Having `The Graph` deployed in the network is also a must.

Hey! We're working on the integration with The Graph currently. Mind if I ping you when it's done to discuss this further?

**Comment by nchamo** [comment]
> > Hey guys! @samisbakedham thanks for raising the idea of Candle deployment.
> > Having `The Graph` deployed in the network is also a must.
> 
> Hey! We're working on the integration with The Graph currently. Mind if I ping you when it's done to discuss this further?

Definitely!

**Comment by 0xged** [comment]
Hey guys - since we are changing a lot the infra right now, I'll close this PR until further news and audits on new infra are done.

**Comment by samisbakedham** [comment]
> Hey guys - since we are changing a lot the infra right now, I'll close this PR until further news and audits on new infra are done.

Infra?

**Comment by samisbakedham** [comment]
> > > Hey guys! @samisbakedham thanks for raising the idea of Candle deployment.
> > > Having `The Graph` deployed in the network is also a must.
> > 
> > 
> > Hey! We're working on the integration with The Graph currently. Mind if I ping you when it's done to discuss this further?
> 
> Definitely!

We have TheGraph support now

**Comment by 0xged** [comment]
> > Hey guys - since we are changing a lot the infra right now, I'll close this PR until further news and audits on new infra are done.
> 
> Infra?

Sorry, Infra on our side I mean Sami. We are doing a whole re-bump!

**Comment by samisbakedham** [comment]
> > > Hey guys - since we are changing a lot the infra right now, I'll close this PR until further news and audits on new infra are done.
> 
> > 
> 
> > Infra?
> 
> 
> 
> Sorry, Infra on our side I mean Sami. We are doing a whole re-bump! 

What's a whole re-bump?

**Pull request closed without merging**
